# Generated by Django 3.1.5 on 2021-01-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_programminglanguage_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=70, unique=True, verbose_name='Shahar nomi'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='url',
            field=models.URLField(unique=True, verbose_name='Ssilka'),
        ),
    ]
